package com.tencent.wxcloudrun.controller;
import com.tencent.wxcloudrun.config.ApiResponse; import com.tencent.wxcloudrun.service.RecipeService; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api") public class RecipeController {
 private final RecipeService service; public RecipeController(RecipeService service){this.service=service;}
 private String user(String h){if(h==null||h.trim().isEmpty())throw new IllegalArgumentException("无法确认微信用户身份，请重新进入小程序");return h;}
 @GetMapping("/users/me") public ApiResponse profile(@RequestHeader(value="X-WX-OPENID",required=false)String u){return ApiResponse.ok(service.userProfile(u));}
 @PostMapping("/users/me") public ApiResponse saveProfile(@RequestHeader(value="X-WX-OPENID",required=false)String u,@RequestBody Map<String,Object>b){return ApiResponse.ok(service.saveUserProfile(u,b.get("nickname")==null?"":String.valueOf(b.get("nickname")),b.get("avatarUrl")==null?"":String.valueOf(b.get("avatarUrl"))));}
 @GetMapping("/recipe-categories") public ApiResponse categories(@RequestHeader(value="X-WX-OPENID",required=false)String u){return ApiResponse.ok(service.categories(user(u)));}
 @PostMapping("/recipe-categories") public ApiResponse createCategory(@RequestHeader(value="X-WX-OPENID",required=false)String u,@RequestBody Map<String,Object>b){return ApiResponse.ok(service.createCategory(u,String.valueOf(b.getOrDefault("name",""))));}
 @GetMapping("/recipes") public ApiResponse list(@RequestHeader(value="X-WX-OPENID",required=false)String u,@RequestParam(required=false)String category,@RequestParam(required=false)String keyword,@RequestParam(defaultValue="false")boolean favorite,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int pageSize){Map<String,Object> q=new HashMap<>();q.put("categoryName",category);q.put("keyword",keyword);q.put("favoriteOnly",favorite);q.put("offset",Math.max(0,page-1)*Math.min(pageSize,100));q.put("pageSize",Math.min(pageSize,100));return ApiResponse.ok(service.list(user(u),q));}
 @GetMapping("/recipes/{id}") public ApiResponse detail(@RequestHeader(value="X-WX-OPENID",required=false)String u,@PathVariable Long id){Map<String,Object> r=service.detail(user(u),id);return r==null?ApiResponse.error("菜谱不存在"):ApiResponse.ok(r);}
 @PostMapping("/recipes") public ApiResponse create(@RequestHeader(value="X-WX-OPENID",required=false)String u,@RequestBody Map<String,Object>b){Object category=b.get("category");if(category==null||!service.categoryExists(user(u),String.valueOf(category)))return ApiResponse.error("菜品分类无效");return ApiResponse.ok(service.create(u,b));}
 @PutMapping("/recipes/{id}") public ApiResponse update(@RequestHeader(value="X-WX-OPENID",required=false)String u,@PathVariable Long id,@RequestBody Map<String,Object>b){Object category=b.get("category");if(category==null||!service.categoryExists(user(u),String.valueOf(category)))return ApiResponse.error("菜品分类无效");return ApiResponse.ok(service.update(u,id,b));}
 @DeleteMapping("/recipes/{id}") public ApiResponse delete(@RequestHeader(value="X-WX-OPENID",required=false)String u,@PathVariable Long id){service.delete(u,id);return ApiResponse.ok();}
 @PostMapping("/recipes/{id}/favorite") public ApiResponse favorite(@RequestHeader(value="X-WX-OPENID",required=false)String u,@PathVariable Long id){Map<String,Object>r=new HashMap<>();r.put("favorited",service.favorite(user(u),id));return ApiResponse.ok(r);}
 @GetMapping("/cooking-records") public ApiResponse records(@RequestHeader(value="X-WX-OPENID",required=false)String u){return ApiResponse.ok(service.records(user(u)));}
 @GetMapping("/cooking-records/{id}") public ApiResponse cookingRecord(@RequestHeader(value="X-WX-OPENID",required=false)String u,@PathVariable Long id){return ApiResponse.ok(service.cookingRecord(user(u),id));}
 @PostMapping("/cooking-records") public ApiResponse addRecord(@RequestHeader(value="X-WX-OPENID",required=false)String u,@RequestBody Map<String,Object>b){return ApiResponse.ok(service.addRecord(user(u),b));}
 @PutMapping("/cooking-records/{id}") public ApiResponse updateCookingRecord(@RequestHeader(value="X-WX-OPENID",required=false)String u,@PathVariable Long id,@RequestBody Map<String,Object>b){return ApiResponse.ok(service.updateCookingRecord(user(u),id,b));}
 @DeleteMapping("/cooking-records") public ApiResponse clear(@RequestHeader(value="X-WX-OPENID",required=false)String u){service.clearRecords(user(u));return ApiResponse.ok();}
 @GetMapping("/statistics") public ApiResponse statistics(@RequestHeader(value="X-WX-OPENID",required=false)String u){return ApiResponse.ok(service.statistics(user(u)));}
 @GetMapping("/recipes/count") public ApiResponse recipeCount(@RequestHeader(value="X-WX-OPENID",required=false)String u){return ApiResponse.ok(service.statistics(user(u)).get("recipeCount"));}
 @GetMapping("/cooking-records/count") public ApiResponse recordCount(@RequestHeader(value="X-WX-OPENID",required=false)String u){return ApiResponse.ok(service.statistics(user(u)).get("cookingRecordCount"));}
}
