package com.tencent.wxcloudrun.service;
import com.tencent.wxcloudrun.dao.RecipeMapper; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.util.*; import java.security.SecureRandom;
@Service public class RecipeService {
 private static final String SHARE_ALPHABET="ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; private static final SecureRandom SHARE_RANDOM=new SecureRandom();
 private final RecipeMapper mapper; public RecipeService(RecipeMapper mapper){this.mapper=mapper;}
 private String user(String u){if(u==null||u.trim().isEmpty())throw new IllegalArgumentException("无法确认微信用户身份，请重新进入小程序");return u;}
 private String requireLoggedIn(String u){if(u==null||u.trim().isEmpty()||mapper.findUserProfile(u)==null)throw new IllegalArgumentException("请先登录后再操作");return u;}
 public Map<String,Object> userProfile(String u){if(u==null||u.trim().isEmpty())return null;return mapper.findUserProfile(u);}
 @Transactional public Map<String,Object> saveUserProfile(String u,String nickname,String avatarUrl){if(u==null||u.trim().isEmpty())throw new IllegalArgumentException("无法确认微信用户身份，请重新进入小程序");if(mapper.findUserProfile(u)!=null)throw new IllegalArgumentException("微信资料已绑定，不能修改");String cleanNickname=nickname==null?"":nickname.trim();if(cleanNickname.isEmpty()||cleanNickname.length()>100)throw new IllegalArgumentException("微信昵称不能为空且不能超过100个字符");Map<String,Object> profile=new HashMap<>();profile.put("openid",u);profile.put("nickname",cleanNickname);profile.put("avatarUrl",avatarUrl==null?"":avatarUrl.trim());mapper.saveUserProfile(profile);Map<String,Object> result=new HashMap<>();result.put("nickname",cleanNickname);result.put("avatarUrl",profile.get("avatarUrl"));return result;}
 public List<Map<String,Object>> categories(String u){return mapper.categories(user(u));}
 @Transactional public Map<String,Object> createCategory(String u,String name){String open=requireLoggedIn(u);String clean=name==null?"":name.trim();if(clean.isEmpty()||clean.length()>30)throw new IllegalArgumentException("分类名称需为1至30个字符");Map<String,Object> p=new HashMap<>();p.put("openid",open);p.put("name",clean);if(mapper.categoryExists(p)>0)throw new IllegalArgumentException("分类已存在");mapper.insertCategory(p);Map<String,Object> result=new HashMap<>();result.put("name",clean);return result;}
 public boolean categoryExists(String u,String name){Map<String,Object> p=new HashMap<>();p.put("openid",user(u));p.put("name",name);return mapper.categoryExists(p)>0;}
 public List<Map<String,Object>> list(String u, Map<String,Object> q){q.put("userOpenid",user(u)); return mapper.list(q);}
 public Map<String,Object> detail(String u,Long id){Map<String,Object> p=new HashMap<>();p.put("userOpenid",user(u));p.put("id",id);Map<String,Object> r=mapper.find(p);if(r!=null){r.put("ingredients",mapper.ingredients(id));r.put("steps",mapper.steps(id));r.put("images",mapper.images(id));}return r;}
 @Transactional public Map<String,Object> create(String u,Map<String,Object> body){String open=requireLoggedIn(u);mapper.upsertUser(open);body.put("userOpenid",open);body.put("isPublic",0);body.putIfAbsent("title",body.get("name"));body.putIfAbsent("categoryName",body.get("category"));mapper.insertRecipe(body);Long id=((Number)body.get("id")).longValue(); addChildren(body.get("ingredients"),id,"ingredient");addChildren(body.get("steps"),id,"step");addChildren(body.get("images"),id,"image");return detail(open,id);}
 @Transactional public Map<String,Object> update(String u,Long id,Map<String,Object> body){String open=requireLoggedIn(u);if(mapper.ownsRecipe(id,open)==0)throw new IllegalArgumentException("菜谱不存在或无权编辑");body.put("id",id);body.put("userOpenid",open);body.putIfAbsent("title",body.get("name"));body.putIfAbsent("categoryName",body.get("category"));mapper.updateRecipe(body);mapper.deleteIngredients(id);mapper.deleteSteps(id);addChildren(body.get("ingredients"),id,"ingredient");addChildren(body.get("steps"),id,"step");return detail(open,id);}
 @Transactional public String createRecipeShare(String u,Long id){String open=requireLoggedIn(u);if(mapper.ownsRecipe(id,open)==0)throw new IllegalArgumentException("菜谱不存在或无权分享");for(int attempt=0;attempt<5;attempt++){StringBuilder code=new StringBuilder(12);for(int i=0;i<12;i++)code.append(SHARE_ALPHABET.charAt(SHARE_RANDOM.nextInt(SHARE_ALPHABET.length())));Map<String,Object> p=new HashMap<>();p.put("shareCode",code.toString());p.put("recipeId",id);p.put("userOpenid",open);if(mapper.insertRecipeShare(p)==1)return code.toString();}throw new IllegalStateException("分享码生成失败，请重试");}
 @Transactional public Map<String,Object> importSharedRecipe(String u,String code){String open=requireLoggedIn(u);String clean=code==null?"":code.trim().toUpperCase(Locale.ROOT);if(!clean.matches("[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{12}"))throw new IllegalArgumentException("分享码格式不正确");Map<String,Object> share=mapper.findRecipeShare(clean);if(share==null)throw new IllegalArgumentException("分享码无效或菜谱已删除");String owner=String.valueOf(share.get("ownerOpenid"));Long recipeId=((Number)share.get("recipeId")).longValue();Map<String,Object> source=detail(owner,recipeId);if(source==null)throw new IllegalArgumentException("分享的菜谱已不存在");String category=String.valueOf(source.getOrDefault("category_name","荤菜"));if(category.isEmpty()||"null".equals(category))category="荤菜";if(!categoryExists(open,category)){Map<String,Object> categoryRow=new HashMap<>();categoryRow.put("openid",open);categoryRow.put("name",category);mapper.insertCategory(categoryRow);if(!categoryExists(open,category))throw new IllegalStateException("无法创建导入菜谱分类");}Map<String,Object> copy=new HashMap<>();copy.put("name",source.get("title"));copy.put("title",source.get("title"));copy.put("category",category);copy.put("categoryName",category);copy.put("coverUrl",source.get("cover_url"));copy.put("difficulty",source.get("difficulty"));copy.put("cookingTime",source.get("cooking_time"));copy.put("ingredients",source.get("ingredients"));copy.put("steps",source.get("steps"));return create(open,copy);}
 @Transactional public void delete(String u,Long id){String open=requireLoggedIn(u);if(mapper.ownsRecipe(id,open)==0)throw new IllegalArgumentException("菜谱不存在或无权删除");mapper.detachCookingRecords(id);mapper.deleteIngredients(id);mapper.deleteSteps(id);mapper.deleteImages(id);mapper.deleteRecipeFavorites(id);if(mapper.deleteRecipe(params(open,id))==0)throw new IllegalArgumentException("菜谱删除失败");}
 private Map<String,Object> params(String open,Long id){Map<String,Object> p=new HashMap<>();p.put("userOpenid",open);p.put("id",id);return p;}
 private void addChildren(Object value,Long id,String type){if(!(value instanceof List))return; int order=0; for(Object o:(List)value){Map m=new HashMap();m.put("recipeId",id); if(o instanceof Map)m.putAll((Map)o); else if("ingredient".equals(type))m.put("name",String.valueOf(o)); else if("step".equals(type))m.put("content",String.valueOf(o)); if("ingredient".equals(type)){m.putIfAbsent("sortOrder",order++);mapper.insertIngredient(m);}else if("step".equals(type)){m.putIfAbsent("stepNo",order++ + 1);mapper.insertStep(m);}else{m.putIfAbsent("sortOrder",order++);mapper.insertImage(m);}}}
 @Transactional public boolean favorite(String u,Long id){String open=user(u);if(mapper.ownsRecipe(id,open)==0)throw new IllegalArgumentException("菜谱不存在或无权收藏");Map<String,Object> p=new HashMap<>();p.put("userOpenid",open);p.put("recipeId",id);if(mapper.favoriteCount(p)>0){mapper.removeFavorite(p);return false;}mapper.addFavorite(p);return true;}
 public List<Map<String,Object>> records(String u){Map<String,Object> p=new HashMap<>();p.put("userOpenid",user(u));return mapper.records(p);}
 public Map<String,Object> cookingRecord(String u,Long id){Map<String,Object> p=new HashMap<>();p.put("userOpenid",user(u));p.put("id",id);Map<String,Object> record=mapper.cookingRecord(p);if(record==null)throw new IllegalArgumentException("做菜记录不存在");return record;}
 @Transactional public Map<String,Object> addRecord(String u,Map<String,Object> b){String open=user(u);b.put("userOpenid",open);Object recipeId=b.get("recipeId");if(recipeId != null){Map<String,Object> query=new HashMap<>();query.put("userOpenid",open);query.put("id",Long.valueOf(String.valueOf(recipeId)));Map<String,Object> recipe=mapper.find(query);if(recipe == null) throw new IllegalArgumentException("菜谱不存在");b.put("recipeTitle",recipe.get("title"));}b.putIfAbsent("note","");b.putIfAbsent("photoUrls","[]");mapper.addRecord(b);return b;}
 @Transactional public Map<String,Object> updateCookingRecord(String u,Long id,Map<String,Object> body){String open=user(u);cookingRecord(open,id);Object ratingValue=body.get("rating");Integer rating=null;if(ratingValue!=null&&!String.valueOf(ratingValue).trim().isEmpty()){try{rating=Integer.valueOf(String.valueOf(ratingValue));}catch(NumberFormatException e){throw new IllegalArgumentException("评分必须为1至5星");}if(rating<1||rating>5)throw new IllegalArgumentException("评分必须为1至5星");}String note=body.get("note")==null?"":String.valueOf(body.get("note"));String photoUrls=body.get("photoUrls")==null?"[]":String.valueOf(body.get("photoUrls"));Map<String,Object> p=new HashMap<>();p.put("id",id);p.put("userOpenid",open);p.put("rating",rating);p.put("note",note);p.put("photoUrls",photoUrls);mapper.updateCookingRecord(p);return cookingRecord(open,id);}
 @Transactional public void deleteCookingRecord(String u,Long id){String open=user(u);cookingRecord(open,id);Map<String,Object> p=new HashMap<>();p.put("id",id);p.put("userOpenid",open);mapper.deleteCookingRecord(p);}
 @Transactional public void clearRecords(String u){mapper.clearRecords(user(u));}
 public Map<String,Object> statistics(String u){String open=user(u);Map<String,Object> r=new LinkedHashMap<>();r.put("recipeCount",mapper.countRecipes(open));r.put("favoriteCount",mapper.countFavorites(open));r.put("cookingRecordCount",mapper.countRecords(open));return r;}
}
